- hosts: targets
  become: true
  tasks:
  - name: Install nodejs
    apt:
      pkg:
      - nodejs
      - npm
      - git
      state: latest
      update_cache: true

  - name: Install puppeteer dependencies
    apt:
      pkg:
      - ca-certificates
      - fonts-liberation
      - libasound2t64
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libexpat1
      - libfontconfig1
      - libgbm1
      - libgcc1
      - libglib2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libstdc++6
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - lsb-release
      - wget
      - xdg-utils
      state: latest
      update_cache: true

  - name: Ensure projects directory
    ansible.builtin.file:
      path: /opt/projects/
      state: directory
      mode: '0755'
      owner: devops

  - name: Clone strava-tools
    become: no
    ansible.builtin.git:
      repo: https://github.com/bengosney/strava-tool.git
      dest: /opt/projects/strava-tool
    register: git_result

  - name: Install npm packages
    become: no
    ansible.builtin.command:
      cmd: npm install
      chdir: /opt/projects/strava-tool
    when: git_result is changed

  - name: Add cron job
    become: no
    cron:
      name: strava-tools-kudos
      minute: '*/15'
      job: node /opt/projects/strava-tool/auto-kudos.js
      state: present
